name: "Bug Report"
description: "File a Bug Report"
title: "[Bug Report]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        You are filing a bug report for the **SA Mod Manager**. For **game issues**, such as a **game crash** or **settings not working**, please report those to their respective repositories.
        [Report SADX Issues Here](https://github.com/X-Hax/sadx-mod-loader)
        [Report SA2 Here Here](https://github.com/X-Hax/sa2-mod-loader) 
  - type: checkboxes
    attributes:
      label: Report Verification
      description: Please confirm that this report you are submitting is for the Mod Manager program (not for either of the games) and verify that you have checked the Issues to ensure this issue has not already been reported.
      options:
        - label: This report is for a bug with the SA Mod Manager.
          required: true
        - label: I have checked and verified this issue has not been reported previously.
          required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of the bug you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Please provide the steps you were taking when the bug occurred. This includes any steps taken the last time the program was operational prior to the bug occurring.
    validations:
      required: true
  - type: dropdown
    id: build
    attributes:
      label: Please select which build you are using.
      multiple: false
      options:
        - Release Build
        - Development Build
  - type: dropdown
    id: os
    attributes:
      label: Please select your Operating System.
      multiple: false
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operation System Information
      description: Please provide the version of your Operating System. If you're using Linux or MacOS, please provide the emulation layer you're using.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Please provide any additional information you believe may pertain to this bug. You can provide screenshots, videos, and any potential logs by clicking this area to highlight it, then dragging the file(s) in.
    validations:
      required: false